server:
  port: 8710
  
spring:
  application:
    name: demo-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/WangKang0711/Repo     # 配置git仓库的地址
          search-paths:                                 # git仓库地址下的相对地址，可以配置多个，用,分割。
          username:                                     # git仓库的账号
          password:                                     # git仓库的密码
  rabbitmq:
    host: 172.16.2.176
    port: 5672
    username: admin
    password: admin123

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.2.176:8761/eureka/   ## 注册中心eurka地址
  instance:
    prefer-ip-address: true

management:
  security:
     enabled: false